import { css } from "styled-components"

export const DOMINANT_COLOR = "#1565C0"
export const DOMINANT_COLOR_LIGHTER = "#1f97ff"
export const TEXT_COLOR = "#9E9E9E"
export const TEXT_COLOR_LIGHTER = "#E0E0E0"
export const HEADER_COLOR = " #37474f"
export const SUBTITLE_COLOR = "#bdbdbd"
export const BACKGROUND_COLOR_DARK = "#041938"
export const BACKGROUND_COLOR_LIGHT = "#FFFFFF"
export const LINE_COLOR_TOTAL = "#BBDEFB"
export const FORM_COLOR_DARK = "#052047"
export const FORM_COLOR_LIGHT = "#e8f3ff"
